# Copyright 2026 Gentoo Authors
# Distributed under the terms of the MIT license
# or the CC-BY-SA-4.0 license (dual-licensed)

when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request, manual]

steps:
  - name: build-and-check
    image: ubuntu:24.04

    commands:
      - apt-get -q -y update
      # Dependencies:
      # librsvg2-bin for rsvg-convert
      # xsltproc for xsltproc
      # libxml2-utils for xmllint
      # tidy for tidy
      - |
        apt-get -q -y install make python3 librsvg2-bin xsltproc \
          libxml2-utils tidy fonts-open-sans
      - make
      - make check
